BBDEVSYS/Controllers/Report/ExportExcelController.cs
using BBDEVSYS.Services.Shared;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace BBDEVSYS.Controllers.Report
{
    public class ExportExcelController : Controller
    {
        // GET: ExportExcel
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ExprotToExcel(int id)

        {

            var model = "";// GetExportModel(id);

            HttpContext.Response.AddHeader("content-disposition", "attachment; filename=XX_" + DateTime.Now.ToString("ddmmyyyy") + ".xls");

            this.Response.ContentType = "application/vnd.ms-excel";
            return View(model);

        }


        //public ActionResult ExportData()
        //{
        //    String constring = ConfigurationManager.ConnectionStrings[ConstantVariableService.ConnStringServer].ConnectionString;
        //    SqlConnection con = new SqlConnection(constring);
        //    string query = "select * From Employee";
        //    DataTable dt = new DataTable();
        //    dt.TableName = "Employee";
        //    con.Open();
        //    SqlDataAdapter da = new SqlDataAdapter(query, con);
        //    da.Fill(dt);
        //    con.Close();
        //    using (XLWorkbook wb = new XLWorkbook())
        //    {
        //        wb.Worksheets.Add(dt);
        //        wb.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        //        wb.Style.Font.Bold = true;

        //        Response.Clear();
        //        Response.Buffer = true;
        //        Response.Charset = "";
        //        Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        //        Response.AddHeader("content-disposition", "attachment;filename= EmployeeReport.xlsx");

        //        using (MemoryStream MyMemoryStream = new MemoryStream())
        //        {
        //            wb.SaveAs(MyMemoryStream);
        //            MyMemoryStream.WriteTo(Response.OutputStream);
        //            Response.Flush();
        //            Response.End();
        //        }
        //    }
        //    return RedirectToAction("Index", "ExportData");
        //}

        private void releaseObject(object obj)
        {
            try
            {
                System.Runtime.InteropServices.Marshal.ReleaseComObject(obj);
                obj = null;
            }
            catch
            {
                obj = null;
            }
            finally
            {
                GC.Collect();
            }
        }



        public ActionResult ExportToExcel()
        {
            var products = new System.Data.DataTable("test");
            products.Columns.Add("col1", typeof(int));
            products.Columns.Add("col2", typeof(string));

            products.Rows.Add(1, "product 1");
            products.Rows.Add(2, "product 2");
            products.Rows.Add(3, "product 3");
            products.Rows.Add(4, "product 4");
            products.Rows.Add(5, "product 5");
            products.Rows.Add(6, "product 6");
            products.Rows.Add(7, "product 7");


            var grid = new GridView();
            grid.DataSource = products;
            grid.DataBind();

            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=MyExcelFile.xls");
            Response.ContentType = "application/ms-excel";

            Response.Charset = "";
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);

            grid.RenderControl(htw);

            Response.Output.Write(sw.ToString());
            Response.Flush();
            Response.End();

            return View("MyView");
        }
        public FileResult ExportResults(int id)
        {
            var model = "";// GetExportModel(id);
            var workbook = new HSSFWorkbook();
            var sheet = workbook.CreateSheet("TestSheet1");
            var headerRow = sheet.CreateRow(0);
            headerRow.CreateCell(0).SetCellValue("ID");
            headerRow.CreateCell(1).SetCellValue("TestDataCol1");
            headerRow.CreateCell(2).SetCellValue("TestDataCol2");
            sheet.CreateFreezePane(0, 1, 0, 1);

            int rowNumber = 1;
            //foreach (var datarow in model.data)
            //{
            //    var datestyle = SetCellStyle(workbook, "dd/MM/yyyy");
            //    var row = sheet.CreateRow(rowNumber++);
            //    row.CreateCell(0).SetCellValue(datarow.Id);
            //    row.CreateCell(1).SetCellValue(datarow.TestData1);
            //    row.CreateCell(2).SetCellValue(datarow.TestData2);

            //    row.Cells[1].CellStyle = datestyle;
            //    row.Cells[2].CellStyle = datestyle;
            //}

            MemoryStream output = new MemoryStream();
            workbook.Write(output);
            return File(output.ToArray(), "application/vnd.ms-excel", "ExcelData.xls");
        }

        public void WriteExcelWithNPOI(DataTable dt, String extension)
        {

            IWorkbook workbook;

            if (extension == "xlsx")
            {
                workbook = new XSSFWorkbook();
            }
            else if (extension == "xls")
            {
                workbook = new HSSFWorkbook();
            }
            else
            {
                throw new Exception("This format is not supported");
            }

            ISheet sheet1 = workbook.CreateSheet("Sheet 1");

            //make a header row
            IRow row1 = sheet1.CreateRow(0);

            for (int j = 0; j < dt.Columns.Count; j++)
            {

                ICell cell = row1.CreateCell(j);
                String columnName = dt.Columns[j].ToString();
                cell.SetCellValue(columnName);
            }

            //loops through data
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                IRow row = sheet1.CreateRow(i + 1);
                for (int j = 0; j < dt.Columns.Count; j++)
                {

                    ICell cell = row.CreateCell(j);
                    String columnName = dt.Columns[j].ToString();
                    cell.SetCellValue(dt.Rows[i][columnName].ToString());
                }
            }

            using (var exportData = new MemoryStream())
            {
                Response.Clear();
                workbook.Write(exportData);
                if (extension == "xlsx") //xlsx file format
                {
                    Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                    Response.AddHeader("Content-Disposition", string.Format("attachment;filename={0}", "ContactNPOI.xlsx"));
                    Response.BinaryWrite(exportData.ToArray());
                }
                else if (extension == "xls")  //xls file format
                {
                    Response.ContentType = "application/vnd.ms-excel";
                    Response.AddHeader("Content-Disposition", string.Format("attachment;filename={0}", "ContactNPOI.xls"));
                    Response.BinaryWrite(exportData.GetBuffer());
                }
                Response.End();
            }
        }


    }
}

BBDEVSYS/Controllers/Report/TimelinessController.cs
using BBDEVSYS.Services.CenterSetting;
using BBDEVSYS.Services.Shared;
using BBDEVSYS.ViewModels.Posting;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BBDEVSYS.Controllers.Report
{
    public class TimelinessController : Controller
    {
        // GET: rptTimeliness
        public ActionResult List()
        {

            return View("~/Views/Report/PaymentPostingTimeliness/TimelinessReport.cshtml");
        }

        public ActionResult SubmitForm(PaymentPostingViewModel formData)
        {

            PaymentPostingService service = new PaymentPostingService();
            //service.ExportReport(formData);

            service.ExportReport(formData);
            return null;

        }

        [HttpGet]
        public FileContentResult ExportToExcel()
        {
            PaymentPostingService service = new PaymentPostingService();
          

            DataTable  dt =  service.ExportReport();

            string g = "";
            string[] columns = dt.Columns.Cast<DataColumn>()
                                 .Select(x => x.ColumnName)
                                 .ToArray();
            byte[] filecontent = ExcelExportHelper.ExportExcel(dt, "Technology", false, columns);
            return File(filecontent, ExcelExportHelper.ExcelContentType, "Technologies.xlsx");
        }

    }
}

BBDEVSYS/Views/Report/PaymentPostingTimeliness/TimelinessReport.cshtml
@model BBDEVSYS.ViewModels.Posting.PaymentPostingViewModel

@{
    ViewBag.Title = ViewBag.Title + BBDEVSYS.Content.text.ResourceText.TitlePaymentPostingTimeliness;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("SubmitForm", "Timeliness", FormMethod.Post, new { enctype = "multipart/form-data", id = "detailForm", @class = "form-horizontal" }))
{
 

    <div class="row">
        <div class="col-xs-12">
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3 class="box-title">@BBDEVSYS.Content.text.ResourceText.TitlePaymentPostingTimeliness</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                     
                        <div class="form-group">
                            <label class="col-xs-12 col-md-2 true-control-label true-require-field">
                                @Html.LabelFor(m => m.StartDate)
                            </label>
                         
                            <div class="col-xs-12 col-md-3">
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    @Html.TextBoxFor(m => m.StartDate, "{0:dd/MM/yyyy}", new { @class = "form-control pull-right datepicker-th" })
                                </div>
                               @* @Html.ValidationMessageFor(m => m.StartDate, "", new { @class = "text-danger" })*@
                            </div>
                          
                        </div>
                        <div class="form-group">
                            <label class="col-xs-12 col-md-2 true-control-label true-require-field">
                                @Html.LabelFor(m => m.EndDate)
                            </label>
                            <div class="col-xs-12 col-md-3">
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    @Html.TextBoxFor(m => m.EndDate, "{0:dd/MM/yyyy}", new { @class = "form-control pull-right datepicker-th" })
                                </div>
                                @* @Html.ValidationMessageFor(m => m.EndDate, "", new { @class = "text-danger" })*@
                            </div>

                        </div>
                        @*
    <div class="form-group">
        <label class="col-xs-12 col-md-2 true-control-label">
            @Html.LabelFor(m => m.EvaluateSearch.YearBE)
        </label>
        <div class="col-xs-12 col-md-2">
            @Html.TextBoxFor(m => m.EvaluateSearch.YearBE, new { @class = "form-control", @readonly = true })
        </div>

        <label class="col-xs-12 col-md-2 true-control-label">
            @Html.LabelFor(m => m.EvaluateSearch.Quarter)
        </label>
        <div class="col-xs-12 col-md-2">
            @Html.TextBoxFor(m => m.EvaluateSearch.Quarter, new { @class = "form-control", @readonly = true })
        </div>
    </div>

    <div class="form-group">
        <label class="col-xs-12 col-md-2 true-control-label ">
            @Html.LabelFor(m => m.OrgGroupText)
        </label>
        <div class="col-xs-12 col-md-6">
            @Html.DropDownListFor(m => m.OrgGroup, new SelectList(Model.OrgSaleGroup, "OrgID", "OrgName"), "", new { @class = "form-control", style = "width:100%;", @onchange = "onChangeGetOrgLevel(this.value)" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-xs-12 col-md-2 true-control-label ">
            @Html.LabelFor(m => m.OrgFractionText)
        </label>
        <div class="col-xs-12 col-md-6">
            @Html.DropDownListFor(m => m.OrgFraction, new SelectList(Model.belowOrgFunction, "OrgID", "OrgName"), @BBDEVSYS.Content.text.ResourceText.SelectedOrgGroup, new { @class = "form-control", style = "width:100%;", @onchange = "onChangeGetOrgSubLevel(this.value)" })
        </div>
    </div>

    <div class="form-group">
        <label class="col-xs-12 col-md-2 true-control-label ">
            @Html.LabelFor(m => m.OrgDivisionPartText)
        </label>
        <div class="col-xs-12 col-md-6">
            @Html.DropDownListFor(m => m.OrgDivisionPart, new SelectList(Model.belowOrgDivision, "OrgID", "OrgName"), @BBDEVSYS.Content.text.ResourceText.SelectedOrgFunction, new { @class = "form-control", style = "width:100%;" })
        </div>
    </div>

                        *@
                    </div>
                </div>
            </div>
        </div>
    </div>

  
    <div class="row">
        <div class="col-xs-2">
            <a href="@Url.Action("ExportToExcel", "Timeliness", new { Area = "Report" })" class="btn btn-block btn-danger btn-sm"><span class="fa fa-file-excel-o"></span>Export</a>
            <button type="button" class="btn btn-block btn-danger btn-sm " id="reportButton" onclick="getActionButton();">
                <span class="fa fa-file-excel-o"></span>
                <span>@BBDEVSYS.Content.text.ResourceText.ButtonReport</span>
            </button>

        </div>
    </div>

    @*<div>
        <div id="messagePopup">
            @Html.Partial("~/Views/Shared/MessagePopup.cshtml")
        </div>
    </div>

  

    @Html.HiddenFor(m => m.ID)*@

}
<script src="~/Content/js/input.initialization.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        //Date picker
        //$('#EndDate').datepicker({
        //    autoclose: true

           
        //})
        //var val = $('#EndDate').val();

        //console.log('display : ' + val)
    });
    function getActionButton() {
        //blockUI();
        var formID = 'detailForm';
        //var message = "";
        var form = $('#' + formID);

        //$.validator.unobtrusive.parse(form);
        //var validator = form.validate();
        //if (form.valid()) {
            var url = '@Url.Action("SubmitForm", "Timeliness", new { Area = "Report" })?' + form.serialize();
            $.ajax({
                contentType: 'json',
                data: form.serialize(),
                //url: url,
                success: function (response) {
                   
                }
            }).done(function (result) {
                window.open(url);
                //unblockUI();
            });
            return false;

        //} else {

        //    for (var i = 0; i < validator.errorList.length; i++) {
        //        message = message + validator.errorList[i].message + "<br />";
        //        unblockUI();
        //    }
        //}
    }
</script>