BBDEVSYS/ViewModels/Authorization/AppCompositeRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations;
using FluentValidation;
using BBDEVSYS.Content.text;
using BBDEVSYS.ViewModels.Shared;
using BBDEVSYS.Models.Entities;
using BBDEVSYS.Services.Shared;

namespace BBDEVSYS.ViewModels.Authorization
{
    [FluentValidation.Attributes.Validator(typeof(AppCompositeRoleViewModelValidator))]
    public class AppCompositeRoleViewModel: IViewModel
    {
        public AppCompositeRoleViewModel()
        {
            AppMenuItems = new List<AppMenuViewModel>();
            StatusValueHelp = new List<ValueHelpViewModel>();
        }

        //Authorization
        public const string RoleForManageData = "Role_MA_App_Composite_Role";
        public const string RoleForDisplayData = "Role_DS_App_Composite_Role";

        [Display(Name = "ACRName", ResourceType = typeof(ResourceText))]
        public string Name { get; set; }
        [Display(Name = "ACEDesc", ResourceType = typeof(ResourceText))]
        public string Description { get; set; }
        [Display(Name = "STATUS", ResourceType = typeof(ResourceText))]
        public string Status { get; set; }

        public bool testcheckbox { get; set; }

        public string StatusText { get; set; }

        public string AppMenuSelectedJSON { get; set; }
        public List<AppMenuViewModel> AppMenuItems { get; set; }

        //Value Help
        public List<ValueHelpViewModel> StatusValueHelp; 
    }

    //Validator
    public class AppCompositeRoleViewModelValidator : AbstractValidator<AppCompositeRoleViewModel>
    {

        public AppCompositeRoleViewModelValidator()
        {
            ValidatorOptions.ResourceProviderType = typeof(ValidatorMessage);
            AppCompositeRoleViewModel model = new AppCompositeRoleViewModel();
            
            RuleFor(m => m.Name).NotEmpty();
            RuleFor(m => m.Description).NotEmpty();
            RuleFor(m => m.Status).NotEmpty();

            UtilityService.SetRuleForStringLength<AppCompositeRoleViewModel, AppCompositeRole>(this);

        }

    }
}

BBDEVSYS/ViewModels/Authorization/AppMenuViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BBDEVSYS.ViewModels.Authorization
{
    public class AppMenuViewModel
    {

        public AppMenuViewModel() {
            IsRoleForManage = false;
            IsRoleForDisplay = false;
            CheckRoleForManage = false;
            CheckRoleForDisplay = false;
        }

        public string MenuCode { get; set; }
        public string ResourceName { get; set; }
        public string MenuText { get; set; }
        public string MenuType { get; set; }
        public string ParentMenuCode { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string RoleForManage { get; set; }
        public string RoleForDisplay { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Area { get; set; }
        public string Icon { get; set; }
        public bool IsRoleForManage { get; set; }
        public bool IsRoleForDisplay { get; set; }
        public bool CheckRoleForManage { get; set; }
        public bool CheckRoleForDisplay { get; set; }
        public int Level { get; set; }
    }
}

BBDEVSYS/ViewModels/Authorization/AssignUserRoleItemViewModel.cs
using BBDEVSYS.Content.text;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using BBDEVSYS.Models.Entities;
using BBDEVSYS.ViewModels.Shared;

namespace BBDEVSYS.ViewModels.Authorization
{
    public class AssignUserRoleItemViewModel:IViewModel
    {
        public AssignUserRoleItemViewModel()
        {
            CompositeRoleList = new List<AppCompositeRole>();
        }
       
        //User Role
        public string Username { get; set; }
        [Display(Name ="STATUS",ResourceType =typeof(ResourceText))]
        public string StatusText { get; set; }
        [Display(Name = "ACRName", ResourceType = typeof(ResourceText))]
        public Nullable<int> CompositeRoleID { get; set; }
        public List<AppCompositeRole> CompositeRoleList { get; set; }
        public string PhotoFileName { get; set; }

        public bool DeleteFlag { get; set; }


    }
}

BBDEVSYS/ViewModels/Authorization/AssignUserRoleViewModel.cs
using BBDEVSYS.Content.text;
using BBDEVSYS.ViewModels.Shared;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BBDEVSYS.ViewModels.Authorization
{
    public class AssignUserRoleViewModel : IViewModel
    {
        public AssignUserRoleViewModel()
        {
            AssignUserTypeList = new List<ValueHelpViewModel>();
            AssignUserRoleItemList = new List<AssignUserRoleItemViewModel>();
            Photo = new AttachmentPhotoViewModel();
        }
        //Authorization
        public const string RoleForManageData = "Role_MA_Assign_User_Role";
        public const string RoleForDisplayData = "Role_DS_Assign_User_Role";

        public const string ProcessCode = "AssignUserRoleProcess";

        [Display(Name = "Code", ResourceType = typeof(ResourceText))]
        public string AssignUserCode { get; set; }
        [Display(Name = "FirstnameTH", ResourceType = typeof(ResourceText))]
        public string AssignUserName { get;set;}
        [Display(Name = "Username", ResourceType = typeof(ResourceText))]
        public string UserName { get; set; }
        public string AssignAvailableReason { get; set; }

        [Display(Name = "Type", ResourceType = typeof(ResourceText))]
        public string AssignUserType { get; set; }
        public string AssignUserRoleIcon { get; set; }

        
        public AttachmentPhotoViewModel Photo { get; set; }
        public List<ValueHelpViewModel> AssignUserTypeList { get;  set; }
        public List<AssignUserRoleItemViewModel> AssignUserRoleItemList { get;  set; }
        public AssignUserRoleItemViewModel AssignUserRoleItem { get; set; }
    }
}

BBDEVSYS/Controllers/Authorization/AppCompositeRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using BBDEVSYS.Services.Authorization;
using BBDEVSYS.ViewModels.Authorization;
using BBDEVSYS.Models.Shared;
using BBDEVSYS.Services.Shared;

namespace BBDEVSYS.Controllers.Authorization
{
    public class AppCompositeRoleController : Controller
    {
        [AuthorizeService(AllowRoleList = new[] { AppCompositeRoleViewModel.RoleForDisplayData, AppCompositeRoleViewModel.RoleForManageData })]
        public ActionResult List()
        {
            ViewBag.Title = UtilityService.GetPagetTitlePrefix(ConstantVariableService.FormStateList);
            ViewBag.DisplayOnly = AuthorizeService.CheckDisplayOnly(new[] { AppCompositeRoleViewModel.RoleForManageData });
            ViewBag.user = User.Identity.Name;
            return View("~/Views/Authorization/AppCompositeRole/AppCompositeRoleList.cshtml");
        }

        //For ajax load list data
        [AuthorizeService(AllowRoleList = new[] { AppCompositeRoleViewModel.RoleForDisplayData, AppCompositeRoleViewModel.RoleForManageData })]
        public string GetList()
        {
            AppCompositeRoleService service = new AppCompositeRoleService();
            return service.GetList();
        }

        [HttpGet]
        [AuthorizeService(AllowRoleList = new[] { AppCompositeRoleViewModel.RoleForDisplayData, AppCompositeRoleViewModel.RoleForManageData })]
        public ActionResult Detail(int recordKey)
        {

            AppCompositeRoleService service = new AppCompositeRoleService();
            AppCompositeRoleViewModel indicatorViewModel = service.InitialDetailView(recordKey, ConstantVariableService.FormStateDisplay);

            if (indicatorViewModel != null)
            {
                ViewBag.Title = UtilityService.GetPagetTitlePrefix(ConstantVariableService.FormStateDisplay);
                return View("~/Views/Authorization/AppCompositeRole/AppCompositeRoleDetail.cshtml", indicatorViewModel);
            }
            else
            {
                ViewBag.Title = UtilityService.GetPagetTitlePrefix(ConstantVariableService.FormStateList);
                //return to List page
                return View("~/Views/Authorization/AppCompositeRole/AppCompositeRoleList.cshtml");
            }

        }

        [HttpGet]
        [AuthorizeService(AllowRoleList = new[] { AppCompositeRoleViewModel.RoleForManageData })]
        public ActionResult Manage(int recordKey, string formState)
        {

            AppCompositeRoleService service = new AppCompositeRoleService();
            AppCompositeRoleViewModel indicatorViewModel = service.InitialDetailView(recordKey, formState);

            if (indicatorViewModel != null)
            {
                ViewBag.Title = UtilityService.GetPagetTitlePrefix(formState);
                return View("~/Views/Authorization/AppCompositeRole/AppCompositeRoleDetail.cshtml", indicatorViewModel);
            }
            else
            {
                ViewBag.Title = UtilityService.GetPagetTitlePrefix(ConstantVariableService.FormStateList);
                //return to List page
                return View("~/Views/Authorization/AppCompositeRole/AppCompositeRoleList.cshtml");
            }

        }

        [HttpPost]
        [AuthorizeService(AllowRoleList = new[] { AppCompositeRoleViewModel.RoleForManageData })]
        public ActionResult SubmitForm(AppCompositeRoleViewModel formData)
        {
            AppCompositeRoleService service = new AppCompositeRoleService();
            ValidationResult result = service.SubmitForm(formData, ModelState);

            return Json(
                new { success = !result.ErrorFlag, responseText = result.Message, errorList = result.ModelStateErrorList },
                JsonRequestBehavior.AllowGet
            );
        }
    }
}

BBDEVSYS/Controllers/Authorization/AssignUserRoleController.cs
using BBDEVSYS.Services.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BBDEVSYS.ViewModels.Authorization;
using BBDEVSYS.Services.Authorization;
using BBDEVSYS.Models.Shared;
using BBDEVSYS.ViewModels.Shared;

namespace BBDEVSYS.Controllers.Authorization
{
    public class AssignUserRoleController : Controller
    {
        // GET: AssignRole
        [AuthorizeService(AllowRoleList = new[] { AssignUserRoleViewModel.RoleForDisplayData, AssignUserRoleViewModel.RoleForManageData })]
        public ActionResult List()
        {
            ViewBag.Title = UtilityService.GetPagetTitlePrefix(ConstantVariableService.FormStateList);
            AssignUserRoleService service = new AssignUserRoleService();
            AssignUserRoleViewModel model = service.InitialListSearch();

            ViewBag.DisplayOnly = AuthorizeService.CheckDisplayOnly(new[] { AssignUserRoleViewModel.RoleForManageData });

            return View("~/Views/Authorization/AssignUserRole/AssignUserRoleList.cshtml", model);
        }
        //For ajax load list data
        [AuthorizeService(AllowRoleList = new[] { AssignUserRoleViewModel.RoleForDisplayData, AssignUserRoleViewModel.RoleForManageData })]
        public string GetList()//string assignUserType)
        {
            AssignUserRoleService service = new AssignUserRoleService();
            return service.GetList();//assignUserType);
        }
        [HttpGet]
        [AuthorizeService(AllowRoleList = new[] { AssignUserRoleViewModel.RoleForDisplayData, AssignUserRoleViewModel.RoleForManageData })]
        public ActionResult Detail(int recordKey, string assignUserRoleCode, string assignUserType)
        {

            AssignUserRoleService service = new AssignUserRoleService();
            AssignUserRoleViewModel assignUserViewModel = service.GetDetail(recordKey, ConstantVariableService.FormStateDisplay, assignUserRoleCode, assignUserType);
            if (assignUserViewModel != null)
            {
                //ViewBag.Title = UtilityService.GetPagetTitlePrefix(ConstantVariableService.FormStateDisplay);
                return View("~/Views/Authorization/AssignUserRole/AssignUserRoleDetail.cshtml", assignUserViewModel);
            }
            else
            { 
                //return to List page
                return List();
            }

        }

        [HttpGet]
        [AuthorizeService(AllowRoleList = new[] { AssignUserRoleViewModel.RoleForManageData })]
        public ActionResult Manage(int recordKey, string formState, string assignUserRoleCode, string assignUserType)
        {
            
                AssignUserRoleService service = new AssignUserRoleService();
                AssignUserRoleViewModel assignUserViewModel = service.GetDetail(recordKey, formState, assignUserRoleCode, assignUserType);
            if (assignUserViewModel != null)
            {
                ViewBag.Title = UtilityService.GetPagetTitlePrefix(formState);
                return View("~/Views/Authorization/AssignUserRole/AssignUserRoleDetail.cshtml", assignUserViewModel);
            }
            else
            {
                //return to List page
                return List();
            }

        }

        [HttpPost]
        [AuthorizeService(AllowRoleList = new[] { AssignUserRoleViewModel.RoleForManageData })]
        public ActionResult SubmitForm(AssignUserRoleViewModel formData)
        {
            AssignUserRoleService service = new AssignUserRoleService();
            ValidationResult result = service.SubmitForm(formData, ModelState);

            return Json(
                new { success = !result.ErrorFlag, responseText = result.Message, errorList = result.ModelStateErrorList },
                JsonRequestBehavior.AllowGet
            );
        }
        public PartialViewResult AddItem()
        {
            AssignUserRoleService service = new AssignUserRoleService();
            AssignUserRoleItemViewModel assignUserViewModel = service.InitialItem();

            return PartialView("~/Views/Authorization/AssignUserRole/AssignUserRoleItem.cshtml", assignUserViewModel);

        }
        public ActionResult GetValueHelpStatus(int roleID)
        {
            AssignUserRoleService service = new AssignUserRoleService();
            AssignUserRoleItemViewModel model = new AssignUserRoleItemViewModel();
            model.StatusText = service.InitialGetRoleStatus(roleID);
            return Json(model, JsonRequestBehavior.AllowGet);
        }
    }
}

BBDEVSYS/Views/Authorization/AssignUserRole/AssignUserRoleDetail.cshtml
@model BBDEVSYS.ViewModels.Authorization.AssignUserRoleViewModel
@{
    ViewBag.Title = ViewBag.Title + BBDEVSYS.Content.text.ResourceText.TitleAssignUserRole;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("SubmitForm", "AssignUserRole", FormMethod.Post, new { enctype = "multipart/form-data", id = "detailForm", @class = "form-horizontal" }))
{
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">@BBDEVSYS.Content.text.ResourceText.TitleAssignUserRole</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="col-xs-12 col-md-3 true-control-label ">
                                @Html.LabelFor(m => m.AssignUserCode)
                            </label>
                            <div class="col-xs-12 col-md-8">
                                @Html.TextBoxFor(m => m.AssignUserCode, new { @class = "form-control ", @readonly = true })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-xs-12 col-md-3 true-control-label">
                                @Html.LabelFor(m => m.AssignUserName)
                            </label>
                            <div class="col-xs-12 col-md-8">
                                @Html.TextBoxFor(m => m.AssignUserName, new { @class = "form-control ", @readonly = true })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-xs-12 col-md-3 true-control-label">
                                @Html.LabelFor(m => m.UserName)
                            </label>
                            <div class="col-xs-12 col-md-8">
                                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control ", @readonly = true })
                            </div>
                        </div>

                    </div>
                </div>



            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <div class="box box-success true-box">
                <div class="box-header with-border">
                    <h3 class="box-title">@BBDEVSYS.Content.text.ResourceText.AssignUserRole</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <button type="button" class="btn btn-success btn-sm authManage" id="addItem">
                                <i class="glyphicon glyphicon-plus"></i>
                                <span class="cust-button-text">เพิ่ม</span>
                            </button>
                            <div>
                                <table class="table table-striped table-striped table-hover dataTable no-footer dtr-inline true-table-detail-item">
                                    <thead>
                                        <tr>
                                            
                                            <th>@Html.LabelFor(m => m.AssignUserRoleItem.CompositeRoleID)</th>
                                            <th>@Html.LabelFor(m => m.AssignUserRoleItem.StatusText)</th>
                                            <th></th> @*For button*@
                                        </tr>
                                    </thead>
                                    <tbody id="itemBody">

                                        @foreach (var item in Model.AssignUserRoleItemList)
                                        {
                                            Html.RenderPartial("~/Views/Authorization/AssignUserRole/AssignUserRoleItem.cshtml", item);
                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <div class="box box-success true-box">
                <div class="box-header with-border">
                    <h3 class="box-title">@BBDEVSYS.Content.text.ResourceText.AssignUserRoleLicense</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="col-xs-12 col-md-2">
                                @Html.Partial("~/Views/Shared/AttachmentPhoto.cshtml", Model.Photo)

                                @Html.HiddenFor(m => m.Photo.PreviewNoPhoto)
                                @Html.HiddenFor(m => m.Photo.PhotoSavedFilename)
                                @Html.HiddenFor(m => m.Photo.FilenameToDelete)
                                @Html.HiddenFor(m => m.Photo.DeletedPhotoFlag)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">

            <button type="button" class="btn btn-warning authDisplay" id="backButton" onclick="goBack('@Model.FormState','@Url.Action("List", "AssignUserRole", new { Area = "Authorization" })');">
                <span class="fa fa-chevron-circle-left"></span>
                <span>@BBDEVSYS.Content.text.ResourceText.ButtonBack</span>
            </button>

            <button type="button" class="btn btn-success authManage" id="saveButton" onclick="detailActionButton('@Model.FormState', '@Model.FormAction', 'detailForm', 'default', 'default', 'default');">
                <span class="glyphicon glyphicon-save"></span>
                <span id="saveButtonText">@BBDEVSYS.Content.text.ResourceText.ButtonSave</span>
            </button>
        </div>
    </div>

    <div>
        <div id="messagePopup">
            @Html.Partial("~/Views/Shared/MessagePopup.cshtml")
        </div>
    </div>

    <div>
        <div id="confirmPopup">
            @Html.Partial("~/Views/Shared/ConfirmActionPopup.cshtml")
        </div>
    </div>
    <div>
        <div id="confirmBackPopup">
            @Html.Partial("~/Views/Shared/ConfirmBackPopup.cshtml")
        </div>
    </div>
    @Html.HiddenFor(m => m.ID)
    @Html.HiddenFor(m => m.FormState)
    @Html.HiddenFor(m => m.FormAction)
    @Html.HiddenFor(m=>m.AssignUserType)

    @Html.HiddenFor(m => m.CREATE_BY)
    @Html.HiddenFor(m => m.CREATE_DATE)
    @Html.HiddenFor(m => m.MODIFIED_BY)
    @Html.HiddenFor(m => m.MODIFIED_DATE)

    @Html.HiddenFor(m => m.AssignUserRoleItem.PhotoFileName)

}

<script type="text/javascript">

    //Callback function when click ok button on confirmation popup
    function okActionCallback() {
        detailOkActionPopupButton($('#FormState').val(), $('#FormAction').val(), 'detailForm', 'GOBACK')
    }

    $(document).ready(function () {

        //Set UI from form state (readonly, editable etc.)
        detailSetFormUI($('#FormState').val())

        $("#addItem").click(function () {
            var $this = $(this);
            $this.button("loading");
            $.ajax({
                url: '@Url.Action("AddItem", "AssignUserRole", new { Area = "Authorization" })',
                cache: false,
                success: function (html) { $("#itemBody").append(html); }
            }).done(function (result) {
                $this.button('reset');
            });
            return false;
        });
    });
</script>

BBDEVSYS/Views/Authorization/AssignUserRole/AssignUserRoleItem.cshtml
@using HtmlHelpers.BeginCollectionItem

@model BBDEVSYS.ViewModels.Authorization.AssignUserRoleItemViewModel

<tr>
    @using (Html.BeginCollectionItem("AssignUserRoleItemList"))
    {

        <td class="col-md-9">
            @Html.DropDownListFor(m => m.CompositeRoleID, new SelectList(Model.CompositeRoleList, "ID", "Name"), "", new { @class = "form-control input-sm col-md-2 CompositeRoleID", style = "width:100%;" }) 
        </td>
        <td class="col-md-2">
            @*@Html.TextBoxFor(m => m.StatusText, new { @class = "form-control StatusText", @readonly = "readonly" })*@
            <text>@Model.StatusText</text>
        </td>
        <td style="text-align:right;" class="true-table-column-fit-content col-md-1">

            <button type="button" class="true-table-detail-icon-button authManage" onclick="deleteItemRow(this)" title="ลบ">
                <i style="vertical-align:middle" class="glyphicon glyphicon-trash"></i>
            </button>
        </td>
        @Html.HiddenFor(m => m.DeleteFlag, new { @class = "detail-item-delete-flag" })
        @Html.HiddenFor(m => m.ID)
        @Html.HiddenFor(m => m.CompositeRoleID, new { @class = "CompositeRoleID" })
    }

</tr>
<script src="~/Content/js/input.initialization.js"></script>

<script>
   
    $(document).ready(function () {
        $('.CompositeRoleID').change(function () {
            var getid = $(this).closest('tr').find('text').attr('data-id', $(this).closest('tr').find('input[name="AssignUserRoleItemList.index"]').attr('value'));
            var id = $(this).closest('tr').find('text').attr('data-id');
            var value = $(this).val();
            if (value != 0) {
                $.getJSON("@Url.Action("GetValueHelpStatus", "AssignUserRole", new { Area = "Authorization" })", { roleID: value }, function (data) {
                    $("[data-id=" + id+"]").text(data.StatusText);
                });
            }

        });

         @*$('.CompositeRoleID').change(function () {
             var id = $(this).closest('tr').find('input[type="text"]').attr('id');
             var value =  $(this).val();
             if (value != 0) {
                 $.getJSON("@Url.Action("GetValueHelpStatus", "AssignUserRole", new { Area = "Authorization" })", { roleID: value }, function (data) {
                     $("#" + id).val(data.StatusText);
                 });
             }

         });*@
        
    });

</script>