BBDEVSYS/ViewModels/Adjustrefund/AdjustrefundUploadViewModel.cs
using BBDEVSYS.Content.text;
using BBDEVSYS.Services.Shared;
using BBDEVSYS.ViewModels.Shared;
using FluentValidation;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BBDEVSYS.ViewModels.Adjustrefund
{
    [FluentValidation.Attributes.Validator(typeof(AdjustrefundUploadViewModelValidator))]
    public class AdjustrefundUploadViewModel : IViewModel
    {
        public AdjustrefundUploadViewModel()
        {

            AttachmentList = new List<AttachmentViewModel>();
            adjList = new List<AdjustrefundUploadViewModelItems>();
            adjDataTable = new DataTable();
            previewDataTable = new DataTable();
            UserRequestList = new List<ValueHelpViewModel>();


            TypeUploadLst = new List<SelectListItem>();

        }
        //Authorization
        public const string RoleForManageData = "Role_MA_Adjust_Refund_Role";
        public const string RoleForDisplayData = "Role_DS_Adjust_Refund_Role";

        public const string ProcessCode = "AdjustrefundUploadProcess";

        [DisplayName("Sheet")]
        public string AttachSheet { get; set; }


        [DisplayName("User Id")]
        public string UserRequest { get; set; }

        [DisplayName("TypeUploadFile")]
        public string TypeUploadFile { get; set; }




        //[Required(ErrorMessage = "Please select file.")]

        //[FileExt(Allow = ".xls,.xlsx", ErrorMessage = "Only excel file")]
        [DisplayName("Browse File")]
        public HttpPostedFileBase[] files { get; set; }
        

        public List<AttachmentViewModel> AttachmentList { get; set; }
        public List<AdjustrefundUploadViewModelItems> adjList { get;  set; }
        public DataTable adjDataTable { get;  set; }
        public DataTable previewDataTable { get; set; }

        public  string NameFormView { get; set; }
        public List<ValueHelpViewModel> UserRequestList { get;  set; }

        public string JsonValue { get; set; }

        public string HeaderSummary { get; set; }

        public string TotalAmount { get; set; }
        public string TotalTransaction { get; set; }

       
        public List<SelectListItem> TypeUploadLst { get;  set; }
    }
    public class AdjustrefundUploadViewModelItems {
        #region Data Field 
        public string SR_STATUS { get; set; }
        public Nullable<System.DateTime> SR_OPEN_DATE { get; set; }
        public string SR_NO { get; set; }
        public string CATEGORY { get; set; }
        public string SUB_CATEGORY { get; set; }
        public string ISSUE { get; set; }
        public string BAN_1 { get; set; }
        public string PRIM_RESOURCE { get; set; }
        public string SR_DETAILS { get; set; }
        public string SR_DIVISION { get; set; }
        public string SR_OWNER { get; set; }
        public string BAN_INCORRECT { get; set; }
        public string BAN_2 { get; set; }
        public Nullable<decimal> AR_BALANCE_1 { get; set; }
        public string BAN_1_1 { get; set; }
        public string CUSTOMER_NAME_1 { get; set; }
        public string ACCOUNT_TYPE_1 { get; set; }
        public string COMP_CODE_1 { get; set; }
        public string AR_BALANCE_1_1 { get; set; }
        public string BEN_STATUS_1 { get; set; }
        public string IDENT_1 { get; set; }
        public string CONV_IND_1 { get; set; }
        public string CONV_CODE_1 { get; set; }
        public string T_FORM_ACCOUNT_BC_ID { get; set; }
        public string BAN_2_1 { get; set; }
        public string CUSTOMER_NAME_2 { get; set; }
        public string ACCOUNT_TYPE_2 { get; set; }
        public string COMP_CODE_2 { get; set; }
        public Nullable<decimal> AR_BALANCE_2 { get; set; }
        public string BEN_STATUS_2 { get; set; }
        public string IDENT_2 { get; set; }
        public string CONV_IND_2 { get; set; }
        public string CONV_CODE_2 { get; set; }
        public string T_TO_ACCOUNT_BC_ID { get; set; }
        public string RECEIPT_NO { get; set; }
        public Nullable<decimal> PAY_AMOUNT { get; set; }
        public Nullable<System.DateTime> DEPOSIT_DATE { get; set; }
        public string SOURCE_ID { get; set; }
        public string DOC_BILL_TYPE { get; set; }
        public string FILE_NAME { get; set; }

        #endregion
    }
    //public class FileExt : ValidationAttribute
    //{
    //    public string Allow;
    //    protected  ValidationResult IsValid(object value, FluentValidation.ValidationContext validationContext)
    //    {
    //        if (value != null)
    //        {
    //            string extension = ((System.Web.HttpPostedFileBase)value).FileName.Split('.')[1];
    //            if (Allow.Contains(extension))
    //                return ValidationResult.Success;
    //            else
    //                return new ValidationResult(ErrorMessage);
    //        }
    //        else
    //            return ValidationResult.Success;
    //    }
    //}
    public class AdjustrefundUploadViewModelValidator : AbstractValidator<AdjustrefundUploadViewModel>
    {
        public AdjustrefundUploadViewModelValidator()
        {

            ValidatorOptions.ResourceProviderType = typeof(ValidatorMessage);
            //InvoiceUploadViewModel model = new InvoiceUploadViewModel();
            //UtilityService.SetRuleForStringLength<InvoiceUploadViewModel, "">(this);
        }
    }
}

BBDEVSYS/Controllers/Adjustrefund/AdjustRefundUploadController.cs
using BBDEVSYS.Models.Shared;
using BBDEVSYS.Services.Adjustrefund;
using BBDEVSYS.Services.Shared;
using BBDEVSYS.ViewModels.Adjustrefund;
using Excel;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace BBDEVSYS.Controllers.Adjustrefund
{
    public class AdjustRefundUploadController : Controller
    {
        [AuthorizeService(AllowRoleList = new[] { AdjustrefundUploadViewModel.RoleForDisplayData, AdjustrefundUploadViewModel.RoleForManageData })]
        // GET: AdjustRefundUpload
        public ActionResult List()
        {
            ViewBag.Title = UtilityService.GetPagetTitlePrefix(ConstantVariableService.FormStateList);

            AdjustrefundUploadViewModel model = new AdjustrefundUploadViewModel();
            AdjustRefundUploadService service = new AdjustRefundUploadService();
            model = service.InitialListSearch();
            model.NameFormView = "AdjustrefundUploadDetail";
            //return View("~/Views/Adjustrefund/Upload.cshtml");
            return View("~/Views/Adjustrefund/AdjustrefundUploadDetail.cshtml", model);
        }

        // GET: AdjustRefundUpload/Details/5
        [AuthorizeService(AllowRoleList = new[] { AdjustrefundUploadViewModel.RoleForDisplayData, AdjustrefundUploadViewModel.RoleForManageData })]
        public ActionResult Details(int id)
        {
            return View();
        }
        [HttpPost]
        [AuthorizeService(AllowRoleList = new[] { AdjustrefundUploadViewModel.RoleForManageData })]
        public ActionResult SubmitForm(AdjustrefundUploadViewModel formData)
        {


            AdjustRefundUploadService service = new AdjustRefundUploadService();
            ValidationResult result = service.SubmitForm(formData, ModelState);

            //return Json(
            //    new { success = !result.ErrorFlag, responseText = result.Message, errorList = result.ModelStateErrorList },
            //    JsonRequestBehavior.AllowGet
            //);
            return new JsonResult()
            {
                Data = new
                {
                    success = !result.ErrorFlag,
                    responseText = result.Message,
                    errorList = result.ModelStateErrorList,
                    dataCallback = result.AdditionalInfo1
                },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                //MaxJsonLength = Int32.MaxValue // Use this value to set your maximum size for all of your Requests
            };
        }

        //[HttpPost]
        [AuthorizeService(AllowRoleList = new[] { AdjustrefundUploadViewModel.RoleForManageData })]
        public ActionResult SubmitMergeForm(AdjustrefundUploadViewModel formData)
        {

            AdjustRefundUploadService service = new AdjustRefundUploadService();


            byte[] filecontent = service.SubmitFormFileContent(formData);

            //DataSet getDataset = new DataSet();

            //getDataset = AdjustRefundUploadService.InitialDataFormViewModel(formData);



            //if (getDataset.Tables.Count > 0)
            //{

            //    filecontent = ExcelExportHelper.ExportExcelMutiSheetData(getDataset, "", false);//, columns);
            //}

            //HttpPostedFileBase file = Request.Files[0];
            //if (file.ContentLength > 0)
            //{
            //    var fileName = Path.GetFileName(file.FileName);
            //    assignment.FileLocation = Path.Combine(
            //        Server.MapPath("~/App_Data/uploads"), fileName);
            //    file.SaveAs(assignment.FileLocation);
            //}

            string shotNameTeam = string.Empty;

            shotNameTeam = SettingService.SetShortName(formData.UserRequest);

            if (filecontent == null)
            {
                return List();
            }
            else
            {
                //DownloadCSV(getDataset.Tables["Fund Transfer Memo"]);
                return File(filecontent, ExcelExportHelper.ExcelContentType, shotNameTeam+ "_Mapping Input_"+DateTime.Now.Date.ToString("yyyyMMdd")+ "_MIS format_Adjust" + ".xlsx");
             
            }
            
        }
       public ActionResult DownloadCSV(DataTable formData)
        {

            AdjustRefundUploadService service = new AdjustRefundUploadService();

            #region export CSV

            DataTable dt = new DataTable();
            dt = formData;// AdjustRefundUploadService.InitialDataFormViewModel(formData).Tables["Fund Transfer Memo"] ;
            //Build the CSV file data as a Comma separated string.
            string csvHeader = string.Empty;
            //Build the CSV file data as a Comma separated string.
            string csvDetails = string.Empty;
            //foreach (DataRow rows in dt.Rows)
            //{
            foreach (DataColumn column in dt.Columns)
            {
                //Add the Header row for CSV file.
                csvDetails += column.ColumnName + ' ';
            }


            //Add new line.
            csvDetails += "\r\n";

            foreach (DataRow row in dt.Rows)
            {
                foreach (DataColumn column in dt.Columns)
                {
                    //Add the Data rows.
                    csvDetails += row[column.ColumnName].ToString().Replace(",", ";") + ' ';
                }

                //Add new line.
                csvDetails += "\r\n";
            }
            //}

            // Download the CSV file.
            //HttpContext.Current.Response.Clear();
            //HttpContext.Current.Response.Buffer = true;
            //HttpContext.Current.Response.AddHeader("content-disposition", "attachment;filename=AR_FNTT_" + DateTime.Now.Date.ToString("yyyyMMdd") + ".csv");
            //HttpContext.Current.Response.Charset = "";
            //HttpContext.Current.Response.ContentType = "application/text";
            //HttpContext.Current.Response.Output.Write(csvDetails);
            //HttpContext.Current.Response.Flush();
            //HttpContext.Current.Response.End();

            #endregion
            
            //string shotNameTeam = string.Empty;

            //shotNameTeam = SettingService.SetShortName(formData.UserRequest);
            if (csvDetails == "")
            {
                return List();
            }
            else
            {
                return File(new System.Text.UTF8Encoding().GetBytes(csvDetails), "text/csv", "AR_FNTT_" + DateTime.Now.Date.ToString("yyyyMMdd") + ".csv");
            }

        }
        // return File(new System.Text.UTF8Encoding().GetBytes(csv), "text/csv", "Report123.csv");
        //    System.IO.FileInfo exportFile = //create your ExportFile
        //return File(exportFile.FullName, "text/csv", string.Format("Export-{0}.csv", DateTime.Now.ToString("yyyyMMdd-HHmmss")));
        public PartialViewResult PreviewData(AdjustrefundUploadViewModel formData)
        {
            AdjustRefundUploadService service = new AdjustRefundUploadService();
            AdjustrefundUploadViewModel model = service.SubmitMergeFormData(formData);
            if (model != null)
            {
                return PartialView("~/Views/Adjustrefund/AdjustrefundUploadItems.cshtml", model);
            }
            else
            {
                return null;
            }

        }
        public ActionResult PreviewUploadMISData(string srData)
        {
            AdjustRefundUploadService service = new AdjustRefundUploadService();
            AdjustrefundUploadViewModel model = service.SubmitPreviewUploadData(srData);

            //if (model != null)
            //{
            //    return PartialView("~/Views/Adjustrefund/AdjustrefundPreviewItems.cshtml", model);
            //}
            //else
            //{
            //    return null;
            //}
            return new JsonResult()
            {
                Data = new 
                {
                    success = true,
                    responseText = "",
                    html = UtilityService.RenderPartialView(this, "~/Views/Adjustrefund/AdjustrefundPreviewItems.cshtml", model)
                },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
               
                MaxJsonLength = Int32.MaxValue // Use this value to set your maximum size for all of your Requests
            };
           // return Json(model, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public ActionResult UploadFiles(HttpPostedFileBase[] files)
        {

            //Ensure model state is valid  
            if (ModelState.IsValid)
            {   //iterating through multiple file collection   
                foreach (HttpPostedFileBase file in files)
                {
                    //Checking file is available to save.  
                    if (file != null)
                    {
                        var InputFileName = Path.GetFileName(file.FileName);
                        var ServerSavePath = Path.Combine(Server.MapPath("~/UploadedFiles/") + InputFileName);
                        //Save file to server folder  
                        file.SaveAs(ServerSavePath);
                        //assigning file uploaded status to ViewBag for showing message to user.  
                        ViewBag.UploadStatus = files.Count().ToString() + " files uploaded successfully.";
                    }

                }
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {

                if (upload != null && upload.ContentLength > 0)
                {

BBDEVSYS/Views/Adjustrefund/AdjustrefundPreviewItems.cshtml
@using HtmlHelpers.BeginCollectionItem
@using System.Data
@using HtmlHelpers.BeginCollectionItem
@*@model  List<BBDEVSYS.ViewModels.Adjustrefund.AdjustrefundUploadViewModel>*@
@model BBDEVSYS.ViewModels.Adjustrefund.AdjustrefundUploadViewModel

@if (Model.previewDataTable != null)
{
    if (Model.previewDataTable.Rows.Count > 0)
    {
        <thead id="uploadItemHeader" style="background-color:#f7bf4f">
            <tr>
                @foreach (DataColumn column in Model.previewDataTable.Columns)
                {
                    <th style="min-width:50px">@column.ColumnName</th>
                }
            </tr>

        </thead>
        <tbody id="previewItemBody">
            @foreach (DataRow item in Model.previewDataTable.Rows)
            {
                <tr>
                    @using (Html.BeginCollectionItem("Model.previewDataTable.Rows"))
                    {
                        foreach (DataColumn col in Model.previewDataTable.Columns)
                        {
                            <td style="width:50px">@item[col.ColumnName]</td>
                        }
                    }
                </tr>
            }
          
            @*<label class="col-xs-12 col-md-2 true-control-label true-require-field"> </label>*@

        </tbody>
 

    }

}
@Html.HiddenFor(m => m.TotalTransaction)
@Html.HiddenFor(m => m.TotalAmount)



<script src="~/Content/js/input.initialization.js"></script>
<script type="text/javascript">


    $(document).ready(function () {

        //Set height of fixed column to equals another column
        var bodyOffset = 17; //padding top + bottom + border in pixel
        var headerOffset = 17; //padding top + bottom + border in pixel
        var $table = $('#previewItemTable');
        var tableClone = $table.clone();
        tableClone.find('tr').each(function (i, elem) {

            if (i != 0) {
                var row = $table.find('tr:eq(' + i + ')');


                var fixColumn = row.find('td:nth-child(2)');
                setFixedColumnHeight(row, fixColumn, bodyOffset);

                fixColumn = row.find('td:nth-child(3)');
                setFixedColumnHeight(row, fixColumn, bodyOffset);

                fixColumn = row.find('td:nth-child(4)');
                setFixedColumnHeight(row, fixColumn, bodyOffset);

            }

        });
        //Change item name for sending to controller
        ModifyCollectionItemName('previewItemBody');

    });
</script>

BBDEVSYS/Views/Adjustrefund/AdjustrefundUploadItemHeader.cshtml
@model List<BBDEVSYS.ViewModels.Adjustrefund.AdjustrefundUploadViewModel>


<tr>
    @*<th style="width:300px; vertical-align: top; text-align: left" class="fixedColumn">@BBDEVSYS.Content.text.ResourceText.STATUS</th>
   *@

    @foreach (var item in Model)
    {
        @*<th style="min-width:200px; vertical-align: top; text-align: center">@Html.Raw(item.ColumnName)</th>*@

    }
</tr>

BBDEVSYS/Views/Adjustrefund/AdjustrefundUploadItems.cshtml
@using HtmlHelpers.BeginCollectionItem
@using System.Data
@using HtmlHelpers.BeginCollectionItem
@*@model  List<BBDEVSYS.ViewModels.Adjustrefund.AdjustrefundUploadViewModel>*@
@model BBDEVSYS.ViewModels.Adjustrefund.AdjustrefundUploadViewModel

@if (Model.adjDataTable != null)
{
    if (Model.adjDataTable.Rows.Count > 0)
    {
        <thead id="uploadItemHeader" style="background-color:#f7bf4f">
            <tr>
                @foreach (DataColumn column in Model.adjDataTable.Columns)
                {
                    <th style="min-width:150px">@column.ColumnName</th>
                }
            </tr>

        </thead>
        <tbody id="uploadItemBody">
            @foreach (DataRow item in Model.adjDataTable.Rows)
            {
                <tr>
                    @using (Html.BeginCollectionItem("Model.adjDataTable.Rows"))
                    {
                        foreach (DataColumn col in Model.adjDataTable.Columns)
                        {
                            <td style="width:auto">@item[col.ColumnName]</td>
                        }
                    }
                </tr>
            }

            @*<label class="col-xs-12 col-md-2 true-control-label true-require-field"> </label>*@

        </tbody>
    }

}




<script src="~/Content/js/input.initialization.js"></script>
<script type="text/javascript">


    $(document).ready(function () {

        //Set height of fixed column to equals another column
        var bodyOffset = 17; //padding top + bottom + border in pixel
        var headerOffset = 17; //padding top + bottom + border in pixel
        var $table = $('#uploadItemTable');
        var tableClone = $table.clone();
        tableClone.find('tr').each(function (i, elem) {

            if (i != 0) {
                var row = $table.find('tr:eq(' + i + ')');


                var fixColumn = row.find('td:nth-child(2)');
                setFixedColumnHeight(row, fixColumn, bodyOffset);

                fixColumn = row.find('td:nth-child(3)');
                setFixedColumnHeight(row, fixColumn, bodyOffset);

                fixColumn = row.find('td:nth-child(4)');
                setFixedColumnHeight(row, fixColumn, bodyOffset);

            }

        });
        //Change item name for sending to controller
        ModifyCollectionItemName('uploadItemBody');

    });
</script>

BBDEVSYS/Views/Adjustrefund/AdjustrefundUploadList.cshtml
@model BBDEVSYS.ViewModels.Adjustrefund.AdjustrefundUploadViewModel
@using BBDEVSYS.Services.Shared
@{
    ViewBag.Title = ViewBag.Title + BBDEVSYS.Content.text.ResourceText.TitleInvoiceUpload;
}
<div class="row">
    <div class="col-xs-12 ">
        <div class="true-list-toolbar col-xs-12">
            <div class="col-xs-12 true-list-toolbar-button">
                <button type="button" class="btn btn-danger authManage" id="createButton">
                    <span class="fa fa-plus"></span>
                    @BBDEVSYS.Content.text.ResourceText.ButtonCreate
                </button>
            </div>
        </div>
        <table id="dataListTable" class="table table-striped table-bordered table-hover table-responsive true-datatable"></table>


    </div>
</div>

<script>

    $(document).ready(function () {

        var columns = [
            { "data": "MonthName", "title": "@BBDEVSYS.Content.text.ResourceText.INV_MONTH", "type": "string", "width": "20%" },
            { "data": "INV_YEAR", "title": "@BBDEVSYS.Content.text.ResourceText.INV_YEAR", "type": "string", "width": "20%" },
            { "data": "UploadByName", "title": "@BBDEVSYS.Content.text.ResourceText.UploadBy", "type": "string", "width": "15%" },
            { "data": "FileName", "title": "@BBDEVSYS.Content.text.ResourceText.FileName", "type": "string", "width": "20%" },
            { "data": "UPLOAD_DATE", "title": "@BBDEVSYS.Content.text.ResourceText.UploadDate", "type": "date-dd-mmm-yyyy", "width": "20%" },

            { "data": null, "defaultContent": getDataTableButton(["display"]), "orderable": false, "width": "5%", "className": "true-dt-button-column" },
            { "data": "ID", "type": "num", "hidden": true }
        ];

        displayDataTable('dataListTable', '@Url.Action("GetList", "InvoiceUpload", new { Area = "Invoice" })', columns);

        //Button action
        //Display
        $('#dataListTable tbody').on('click', '.true-dt-button-display', function () {
            var id = $(this).GetDatatableData()["ID"];

            var url = '@Url.Action("Detail", "InvoiceUpload", new { Area = "Invoice" })?recordKey=' + id;

            redirectTo(url);
        });


        //Create
        $('#createButton').click(function () {
            var recordKey = $('#recordKey').val(0);
            $('#formState').val('@ConstantVariableService.FormStateCreate');

            var url = '@Url.Action("Manage", "InvoiceUpload", new { Area = "Invoice" })?recordKey=0&formState=' + '@ConstantVariableService.FormStateCreate';

            redirectTo(url);
        });

        //Edit
        $('#dataListTable tbody').on('click', '.true-dt-button-edit', function () {
            var id = $(this).GetDatatableData()["ID"];

            var url = '@Url.Action("Manage", "InvoiceUpload", new { Area = "Invoice" })?recordKey=' + id + '&formState=' + '@ConstantVariableService.FormStateEdit';

            redirectTo(url);
        });

        //Copy
        $('#dataListTable tbody').on('click', '.true-dt-button-copy', function () {
            var id = $(this).GetDatatableData()["ID"];

            var url = '@Url.Action("Manage", "InvoiceUpload", new { Area = "Invoice" })?recordKey=' + id + '&formState=' + '@ConstantVariableService.FormStateCopy';

            redirectTo(url);
        });

        //Delete
        $('#dataListTable tbody').on('click', '.true-dt-button-delete', function () {
            var id = $(this).GetDatatableData()["ID"];


            var url = '@Url.Action("Manage", "InvoiceUpload", new { Area = "Invoice" })?recordKey=' + id + '&formState=' + '@ConstantVariableService.FormStateDelete';

            redirectTo(url);
        });

        //var SpinBtn = ["display", "edit", "delete"];
        //loadingButton(SpinBtn);

        var allButton = ["display"];
        var SpinBtn = ['display'];
        loadingButton(allButton, SpinBtn);
    });


</script>

BBDEVSYS/Views/Adjustrefund/Upload.cshtml
@model System.Data.DataTable
@using System.Data;

@{
    ViewBag.Title = ""/* ViewBag.Title + BBDEVSYS.Content.text.ResourceText.TitleAdjustrefundUpload*/;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Upload", "AdjustRefundUpload", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <div class="form-group">
        <input type="file" id="dataFile" name="upload" />
    </div>

    <div class="form-group">
        <input type="submit" value="Upload" class="btn btn-default" />
    </div>

    if (Model != null)
    {
        <table>
            <thead>
                <tr>
                    @foreach (DataColumn col in Model.Columns)
                    {
                        <th>@col.ColumnName</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (DataRow row in Model.Rows)
                {
                    <tr>
                        @foreach (DataColumn col in Model.Columns)
                        {
                            <td>@row[col.ColumnName]</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    }
}