BBDEVSYS/ViewModels/InvoiceUpload/InvoiceUploadItemViewModel.cs
using BBDEVSYS.Content.text;
using BBDEVSYS.Models.Entities;
using BBDEVSYS.Services.Shared;
using BBDEVSYS.ViewModels.Shared;
using FluentValidation;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BBDEVSYS.ViewModels.InvoiceUpload
{
    [FluentValidation.Attributes.Validator(typeof(InvoiceUploadItemViewModelValidator))]
    public class InvoiceUploadItemViewModel : IViewModel
    {

        public InvoiceUploadItemViewModel() { }
        
        public int INV_UPLOAD_ID { get; set; }
        public string INV_NO { get; set; }
        public string PRO_NO { get; set; }
        public string CCT_CODE { get; set; }
        public string COMPANY_CODE { get; set; }
        //public Nullable<int> INV_MONTH { get; set; }
        //public Nullable<int> INV_YEAR { get; set; }

        public string INV_MONTH { get; set; }
        public string INV_YEAR { get; set; }

        public string PAYMENT_ITEMS_CODE { get; set; }
        public string INV_REC_BY { get; set; }
        //public Nullable<System.DateTime> INV_REC_DATE { get; set; }
        public string INV_REC_DATE { get; set; }

        public string PRO_REC_DATE { get; set; }

        public string INV_APPROVED_BY { get; set; }

        //public Nullable<System.DateTime> INV_APPROVED_DATE { get; set; }
        //public Nullable<System.DateTime> INV_DUE_DATE { get; set; }
        public string INV_APPROVED_DATE { get; set; }
        public string INV_DUE_DATE { get; set; }
        public string PRO_DUE_DATE { get; set; }

        public string IS_STATUS { get; set; }
        public string CONDITION_PYM { get; set; }
        //public Nullable<decimal> NET_AMOUNT { get; set; }
        //public Nullable<decimal> WHT { get; set; }
        //public Nullable<decimal> DEDUCT_WHT_AMOUNT { get; set; }

        //public Nullable<decimal> INCLUDE_VAT_AMOUNT { get; set; }
        //public Nullable<decimal> VAT { get; set; }
        //public Nullable<System.DateTime> PRO_REC_DATE { get; set; }

        //public Nullable<decimal> TRANSACTIONS { get; set; }
        //public Nullable<decimal> ACTUAL_AMOUNT { get; set; }
        //public Nullable<decimal> RATE_TRANS { get; set; }
        //public Nullable<decimal> RATE_AMT { get; set; }
        //public Nullable<decimal> TOTAL_CHARGE_AMOUNT { get; set; }

        public string NET_AMOUNT { get; set; }
        public string WHT { get; set; }
        public string DISCOUNT { get; set; }
        public string DEDUCT_WHT_AMOUNT { get; set; }

        public string INCLUDE_VAT_AMOUNT { get; set; }
        public string VAT { get; set; }

        public string TRANSACTIONS { get; set; }
        public string ACTUAL_AMOUNT { get; set; }
        public string RATE_TRANS { get; set; }
        public string RATE_AMT { get; set; }
        public string TOTAL_CHARGE_AMOUNT { get; set; }

        public string REMARK { get; set; }
        public string CURRENCY { get; set; }
        public string PAYMENT_ITEMS_FEE_ITEM { get; set; }
        public Nullable<int> SEQUENCE { get; set; }


        public string FEE { get; set; }
        public string CHARGED { get; set; }
        public string CHANNELS { get; set; }

        public string GL_ACCOUNT { get; set; }
        public string FUND_CODE { get; set; }

        public bool DeleteFlag { get; set; }
        public string ItemIndex { get; set; }

        public string Message { get; set; }
        public string MessageAt { get; set; }
        public bool ErrorFlag { get; set; }


    }
    public class InvoiceUploadItemViewModelValidator : AbstractValidator<InvoiceUploadItemViewModel>
    {
        public InvoiceUploadItemViewModelValidator()
        {
            ValidatorOptions.ResourceProviderType = typeof(ValidatorMessage);
            InvoiceUploadItemViewModel model = new InvoiceUploadItemViewModel();



            UtilityService.SetRuleForStringLength<InvoiceUploadItemViewModel, FEE_INVOICE_UPLOAD_ITEM_LOG>(this);
        }
    }
}

BBDEVSYS/ViewModels/InvoiceUpload/InvoiceUploadViewModel.cs
using BBDEVSYS.Content.text;
using BBDEVSYS.Services.Shared;
using BBDEVSYS.ViewModels.Shared;
using FluentValidation;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BBDEVSYS.ViewModels.InvoiceUpload
{
    [FluentValidation.Attributes.Validator(typeof(InvoiceUploadViewModelValidator))]
    public class InvoiceUploadViewModel:IViewModel
    {
        public InvoiceUploadViewModel()
        {
            InvoiceUploadItemList = new List<InvoiceUploadItemViewModel>();
            AttachmentList = new List<AttachmentViewModel>();

            MonthLst = new List<SelectListItem>();
            YearLst = new List<SelectListItem>();
            CompanyLst = new List<SelectListItem>();
            UserApprovedList = new List<SelectListItem>();
        }
        //Authorization
        public const string RoleForManageData = "Role_MA_Invoice_Upload";
        public const string RoleForDisplayData = "Role_DS_Invoice_Upload";

        public const string ProcessCode = "InvoiceUploadProcess";
        
        [Display(Name = "INV_MONTH", ResourceType = typeof(ResourceText))]
        public Nullable<int> INV_MONTH { get; set; }
        [Display(Name = "INV_YEAR", ResourceType = typeof(ResourceText))]
        public Nullable<int> INV_YEAR { get; set; }
        [Display(Name = "INV_YEAR", ResourceType = typeof(ResourceText))]
        public string COMPANY_CODE { get; set; }
        [Display(Name = "REMARK", ResourceType = typeof(ResourceText))]
        public string REMARK { get; set; }
        public string CompanyName { get; set; }
        public string MonthName { get; set; }

        public string UPLOAD_BY { get; set; }
        public Nullable<System.DateTime> UPLOAD_DATE { get; set; }

        public string UploadStatus { get; set; }

        public string Message { get; set; }

        //Text
        public string InvoiceTypeName { get; set; }
        public string UploadByName { get; set; }

        //ValueHelpList
        public List<InvoiceUploadItemViewModel> InvoiceUploadItemList { get; set; }
        public List<AttachmentViewModel> AttachmentList { get; set; }
        public List<SelectListItem> MonthLst { get; set; }
        public List<SelectListItem> YearLst { get; set; }
        public List<SelectListItem> CompanyLst { get; set; }
        public List<SelectListItem> UserApprovedList { get; set; }
        //Screen 
        public virtual bool UserSuperAdmin { get; set; }
        public virtual string FileName { get; set; }
    }

    public class InvoiceUploadViewModelValidator : AbstractValidator<InvoiceUploadViewModel>
    {
        public InvoiceUploadViewModelValidator()
        {

            ValidatorOptions.ResourceProviderType = typeof(ValidatorMessage);
            InvoiceUploadViewModel model = new InvoiceUploadViewModel();
            //UtilityService.SetRuleForStringLength<InvoiceUploadViewModel, "">(this);
        }
    }
}

BBDEVSYS/Controllers/Invoice/InvoiceUploadController.cs
using BBDEVSYS.Models.Shared;
using BBDEVSYS.Services.Invoice;
using BBDEVSYS.Services.Shared;
using BBDEVSYS.ViewModels.InvoiceUpload;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BBDEVSYS.Controllers.Invoice
{
    public class InvoiceUploadController : Controller
    {
        // GET: InvoiceUpload
        [AuthorizeService(AllowRoleList = new[] { InvoiceUploadViewModel.RoleForDisplayData, InvoiceUploadViewModel.RoleForManageData })]
        public ActionResult List()
        {
            ViewBag.Title = UtilityService.GetPagetTitlePrefix(ConstantVariableService.FormStateList);
            ViewBag.DisplayOnly = AuthorizeService.CheckDisplayOnly(new[] { InvoiceUploadViewModel.RoleForManageData });
            return View("~/Views/InvoiceUpload/InvoiceUploadList.cshtml");
        }
        //For ajax load list data
        [AuthorizeService(AllowRoleList = new[] { InvoiceUploadViewModel.RoleForDisplayData, InvoiceUploadViewModel.RoleForManageData })]
        public string GetList()
        {
            InvoiceUploadService service = new InvoiceUploadService();
            return service.GetList();
        }
        [HttpGet]
        [AuthorizeService(AllowRoleList = new[] { InvoiceUploadViewModel.RoleForDisplayData, InvoiceUploadViewModel.RoleForManageData })]
        public ActionResult Detail(int recordKey)
        {
            InvoiceUploadService service = new InvoiceUploadService();
            InvoiceUploadViewModel model = service.InitialDetailView(recordKey, ConstantVariableService.FormStateDisplay);
            ViewBag.Title = UtilityService.GetPagetTitlePrefix(ConstantVariableService.FormStateDisplay);
            return View("~/Views/InvoiceUpload/InvoiceUploadDetail.cshtml", model);
        }
        [HttpGet]
        [AuthorizeService(AllowRoleList = new[] { InvoiceUploadViewModel.RoleForManageData })]
        public ActionResult Manage(int recordKey, string formState)
      {
            InvoiceUploadService service = new InvoiceUploadService();
            InvoiceUploadViewModel model = service.InitialDetailView(recordKey, formState);
            ViewBag.Title = UtilityService.GetPagetTitlePrefix(formState);
            return View("~/Views/InvoiceUpload/InvoiceUploadDetail.cshtml", model);
        }

        // [AuthorizeService(AllowRoleList = new[] { InvoiceUploadViewModel.RoleForManageData })]
        [HttpPost]
        [AuthorizeService(AllowRoleList = new[] { InvoiceUploadViewModel.RoleForManageData })]
        public ActionResult SubmitForm(InvoiceUploadViewModel formData)
        {
            InvoiceUploadService service = new InvoiceUploadService();
            ValidationResult resul = service.SubmitForm(formData, ModelState);

            return Json(
                new { success = !resul.ErrorFlag, responseText = resul.Message, errorList = resul.ModelStateErrorList },
                JsonRequestBehavior.AllowGet
                );
        }



        public ActionResult ImportExcel(string fileName)
        {
            List<InvoiceUploadItemViewModel> uploadInvoiceItemViewModel = new List<InvoiceUploadItemViewModel>();
            InvoiceUploadService service = new InvoiceUploadService();
            var result = service.ImportExcel(fileName);

            if (!result.ErrorFlag)
            {
                uploadInvoiceItemViewModel = result.ReturnResult;
                

                return new JsonResult()
                {
                    Data = new
                    {
                        success = !result.ErrorFlag,
                        responseText = result.Message,
                        html = UtilityService.RenderPartialView(this, "~/Views/InvoiceUpload/InvoiceUploadItems.cshtml", uploadInvoiceItemViewModel)
                    },
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                    MaxJsonLength = Int32.MaxValue // Use this value to set your maximum size for all of your Requests
                };
            }
            else
            {
                return Json(
                    new
                    {
                        success = !result.ErrorFlag,
                        responseText = result.Message,
                        html = "",
                        errorList = result.ModelStateErrorList
                    },
                    JsonRequestBehavior.AllowGet);
            }
        }
        //public PartialViewResult GetUploadItemHeader(int month = 0,int year =0)
        //{
        //    InvoiceUploadService service = new InvoiceUploadService();
        //    var columnList = service.GetUploadItemHeader(month, year);
        //    return PartialView("~/Views/InvoiceUpload/InvoiceUploadItemHeader.cshtml", columnList);

        //}
        //public ActionResult GetWarehouse(string matType)
        //{
        //    InvoiceUploadService service = new InvoiceUploadService();
        //    InvoiceUploadViewModel model = new InvoiceUploadViewModel();
        //    model = service.InitialWarehouse(matType);
        //    return Json(model, JsonRequestBehavior.AllowGet);
        //}
    }
}

BBDEVSYS/Views/InvoiceUpload/InvoiceUploadItemHeader.cshtml
@model List<BBDEVSYS.ViewModels.InvoiceUpload.InvoiceUploadItemViewModel>


<tr>
    @*<th style="width:300px; vertical-align: top; text-align: left" class="fixedColumn">@BBDEVSYS.Content.text.ResourceText.STATUS</th>
    <th style="min-width:100px; vertical-align: top; text-align: left" class="fixedColumn">@BBDEVSYS.Content.text.ResourceText.ShopCode</th>
    <th style="min-width:200px; vertical-align: top; text-align: left" class="fixedColumn">@BBDEVSYS.Content.text.ResourceText.Shop</th>
    <th style="min-width:800px; vertical-align: top; text-align: left" class="checkHeaderHeight">@BBDEVSYS.Content.text.ResourceText.JobDescription</th>
    <th style="min-width:200px; vertical-align: top; text-align: left">@BBDEVSYS.Content.text.ResourceText.JobShopProposal</th>*@
    <th style="min-width:200px; text-align:left;" class="fixedColumn colStatus">@BBDEVSYS.Content.text.ResourceText.STATUS</th>
    <th style="min-width:190px;" class="fixedColumn ">@BBDEVSYS.Content.text.ResourceText.CHANNELS</th>
    <th style="min-width:300px;" class="fixedColumn ">@BBDEVSYS.Content.text.ResourceText.FEE</th>
    <th style="min-width:790px;" class="checkHeaderHeight colStatusNext">@BBDEVSYS.Content.text.ResourceText.Charge</th>
    @*<th style="min-width:150px;">@BBDEVSYS.Content.text.ResourceText.PricePerUnit</th>
        <th style="min-width:150px;">@BBDEVSYS.Content.text.ResourceText.PickUpDate</th>
        <th style="min-width:150px;">@BBDEVSYS.Content.text.ResourceText.BudgetCostCenter</th>
        <th style="min-width:150px;">@BBDEVSYS.Content.text.ResourceText.PickUpOrg</th>*@

    @foreach (var item in Model)
    {
        <th style="min-width:200px; vertical-align: top; text-align: center">@Html.Raw(item.ColumnName)</th>

    }
</tr>

BBDEVSYS/Views/InvoiceUpload/InvoiceUploadItems.cshtml
@using HtmlHelpers.BeginCollectionItem
@model List<BBDEVSYS.ViewModels.InvoiceUpload.InvoiceUploadItemViewModel>

@if (Model.Any())
{
    foreach (var item in Model)
    {
        <tr>
            @using (Html.BeginCollectionItem("InvoiceUploadItemList"))
            {
                <td style="width:200px;" class="colStatus">@Html.Raw(item.Message)</td>
                <td style="width:100px;">@item.INV_MONTH</td>
                <td style="width:100px;">@item.INV_YEAR</td>
                <td>@item.CHANNELS</td>
                <td>@item.FEE</td>
                <td>@item.SEQUENCE</td>
                <td>@item.CHARGED</td>
                <td>@item.TRANSACTIONS</td>
                <td>@item.RATE_TRANS</td>
                <td>@item.ACTUAL_AMOUNT</td>
                <td>@item.RATE_AMT</td>
                <td>@item.TOTAL_CHARGE_AMOUNT</td>
                <td>@item.NET_AMOUNT</td>
                <td>@item.DEDUCT_WHT_AMOUNT</td>
                <td>@item.CURRENCY</td>
                <td>@item.INCLUDE_VAT_AMOUNT</td>
                <td>@item.GL_ACCOUNT</td>
                <td>@item.CCT_CODE</td>
                <td>@item.FUND_CODE</td>
                <td>@item.COMPANY_CODE</td>
                <td>@item.INV_NO</td>
                <td>@item.PRO_NO</td>
                <td>@item.PRO_REC_DATE</td>
                <td>@item.INV_REC_BY</td>
                <td>@item.INV_REC_DATE</td>
                <td>@item.INV_APPROVED_BY</td>
                <td>@item.INV_APPROVED_DATE</td>
                <td>@item.INV_DUE_DATE</td>
                <td>@item.CONDITION_PYM</td>
                <td>@item.VAT</td>
                <td>@item.WHT</td>
                <td>@item.REMARK</td>
                <td>@item.DISCOUNT</td>





                @Html.HiddenFor(m => item.ID)
                @Html.HiddenFor(m => item.ErrorFlag)
               //@Html.HiddenFor(m => item.Message) @*Message contain html code, cannot send value to backend*@

                @Html.HiddenFor(m => item.INV_MONTH)
                @Html.HiddenFor(m => item.INV_YEAR)
                @Html.HiddenFor(m => item.CHANNELS)
                @Html.HiddenFor(m => item.FEE)
                @Html.HiddenFor(m => item.SEQUENCE)
                @Html.HiddenFor(m => item.TRANSACTIONS)
                @Html.HiddenFor(m => item.RATE_AMT)
                @Html.HiddenFor(m => item.RATE_TRANS)
                @Html.HiddenFor(m => item.ACTUAL_AMOUNT)
                @Html.HiddenFor(m => item.TOTAL_CHARGE_AMOUNT)
                @Html.HiddenFor(m => item.NET_AMOUNT)
                @Html.HiddenFor(m => item.DEDUCT_WHT_AMOUNT)
                @Html.HiddenFor(m => item.CURRENCY)
                @Html.HiddenFor(m => item.INCLUDE_VAT_AMOUNT)
                @Html.HiddenFor(m => item.GL_ACCOUNT)
                @Html.HiddenFor(m => item.CCT_CODE)
                @Html.HiddenFor(m => item.FUND_CODE)
                @Html.HiddenFor(m => item.COMPANY_CODE)
                @Html.HiddenFor(m => item.INV_NO)
                @Html.HiddenFor(m => item.PRO_NO)
                @Html.HiddenFor(m => item.PRO_REC_DATE)
                @Html.HiddenFor(m => item.INV_REC_BY)
                @Html.HiddenFor(m => item.INV_REC_DATE)
                @Html.HiddenFor(m => item.INV_APPROVED_BY)

                @Html.HiddenFor(m => item.INV_DUE_DATE)
                @Html.HiddenFor(m => item.INV_APPROVED_DATE)
                @Html.HiddenFor(m => item.CONDITION_PYM)
                @Html.HiddenFor(m => item.VAT)
                @Html.HiddenFor(m => item.WHT)
                @Html.HiddenFor(m => item.REMARK)
                @Html.HiddenFor(m => item.DISCOUNT)
                @Html.HiddenFor(m => item.IS_STATUS)


            }
        </tr>

    }
}


<script src="~/Content/js/input.initialization.js"></script>
<script type="text/javascript">


    $(document).ready(function () {

        //Set height of fixed column to equals another column
        var bodyOffset = 17; //padding top + bottom + border in pixel
        var headerOffset = 17; //padding top + bottom + border in pixel
        var $table = $('#uploadItemTable');
        var tableClone = $table.clone();
        tableClone.find('tr').each(function (i, elem) {

            if (i != 0) {
                var row = $table.find('tr:eq(' + i + ')');


                var fixColumn = row.find('td:nth-child(2)');
                setFixedColumnHeight(row, fixColumn, bodyOffset);

                fixColumn = row.find('td:nth-child(3)');
                setFixedColumnHeight(row, fixColumn, bodyOffset);

                fixColumn = row.find('td:nth-child(4)');
                setFixedColumnHeight(row, fixColumn, bodyOffset);

            }

        });
        //Change item name for sending to controller
        ModifyCollectionItemName('uploadItemBody');

    });
</script>

BBDEVSYS/Views/InvoiceUpload/InvoiceUploadList.cshtml
@model BBDEVSYS.ViewModels.InvoiceUpload.InvoiceUploadViewModel
@using BBDEVSYS.Services.Shared
@{
    ViewBag.Title = ViewBag.Title + BBDEVSYS.Content.text.ResourceText.TitleInvoiceUpload;
}
<div class="row">
    <div class="col-xs-12 ">
        <div class="true-list-toolbar col-xs-12">
            <div class="col-xs-12 true-list-toolbar-button">
                <button type="button" class="btn btn-danger authManage" id="createButton">
                    <span class="fa fa-plus"></span>
                    @BBDEVSYS.Content.text.ResourceText.ButtonCreate
                </button>
            </div>
        </div>
        <table id="dataListTable" class="table table-striped table-bordered table-hover table-responsive true-datatable"></table>


    </div>
</div>

<script>

    $(document).ready(function () {

        var columns = [
            { "data": "MonthName", "title": "@BBDEVSYS.Content.text.ResourceText.INV_MONTH", "type": "string", "width": "20%" },
            { "data": "INV_YEAR", "title": "@BBDEVSYS.Content.text.ResourceText.INV_YEAR", "type": "string", "width": "20%" },
            { "data": "UploadByName", "title": "@BBDEVSYS.Content.text.ResourceText.UploadBy", "type": "string", "width": "15%" },
            { "data": "FileName", "title": "@BBDEVSYS.Content.text.ResourceText.FileName", "type": "string", "width": "20%" },
            { "data": "UPLOAD_DATE", "title": "@BBDEVSYS.Content.text.ResourceText.UploadDate", "type": "date-dd-mmm-yyyy", "width": "20%" },

            { "data": null, "defaultContent": getDataTableButton(["display"]), "orderable": false, "width": "5%", "className": "true-dt-button-column" },
            { "data": "ID", "type": "num", "hidden": true }
        ];

        displayDataTable('dataListTable', '@Url.Action("GetList", "InvoiceUpload", new { Area = "Invoice" })', columns);

        //Button action
        //Display
        $('#dataListTable tbody').on('click', '.true-dt-button-display', function () {
            var id = $(this).GetDatatableData()["ID"];

            var url = '@Url.Action("Detail", "InvoiceUpload", new { Area = "Invoice" })?recordKey=' + id;

            redirectTo(url);
        });


        //Create
        $('#createButton').click(function () {
            var recordKey = $('#recordKey').val(0);
            $('#formState').val('@ConstantVariableService.FormStateCreate');

            var url = '@Url.Action("Manage", "InvoiceUpload", new { Area = "Invoice" })?recordKey=0&formState=' + '@ConstantVariableService.FormStateCreate';

            redirectTo(url);
        });

        //Edit
        $('#dataListTable tbody').on('click', '.true-dt-button-edit', function () {
            var id = $(this).GetDatatableData()["ID"];

            var url = '@Url.Action("Manage", "InvoiceUpload", new { Area = "Invoice" })?recordKey=' + id + '&formState=' + '@ConstantVariableService.FormStateEdit';

            redirectTo(url);
        });

        //Copy
        $('#dataListTable tbody').on('click', '.true-dt-button-copy', function () {
            var id = $(this).GetDatatableData()["ID"];

            var url = '@Url.Action("Manage", "InvoiceUpload", new { Area = "Invoice" })?recordKey=' + id + '&formState=' + '@ConstantVariableService.FormStateCopy';

            redirectTo(url);
        });

        //Delete
        $('#dataListTable tbody').on('click', '.true-dt-button-delete', function () {
            var id = $(this).GetDatatableData()["ID"];


            var url = '@Url.Action("Manage", "InvoiceUpload", new { Area = "Invoice" })?recordKey=' + id + '&formState=' + '@ConstantVariableService.FormStateDelete';

            redirectTo(url);
        });

        //var SpinBtn = ["display", "edit", "delete"];
        //loadingButton(SpinBtn);

        var allButton = ["display"];
        var SpinBtn = ['display'];
        loadingButton(allButton, SpinBtn);
    });


</script>